# baseline = load_graph(name='baseline')

# base_graph.remove_edges_from(removed_edges)
# print(node_list[0])
# print(base_graph.edges(node_list[0]))
# print(edge_list)
# reverse_edge_list = sorted(edge_list, key=lambda x: x[1], reverse=True)
# print(reverse_edge_list[:1000])
# edge_list = np.array(edge_list)
# base_graph = load_graph(name='baseline')
# print(list(nx.connected_components(base_graph)))
# plt.subplot(121)
# nx.draw(base_graph, with_labels=True)
# plt.show()
# print(list(base_graph.nodes))
# print(list(base_graph.edges))
# print(base_graph.degree(base_graph.nodes))
# print(f'After removal: {len(base_graph.edges)}')
